version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET=${DJANGO_SECRET}
    command: python manage.py runserver 0.0.0.0:8000
