# Generated by Django 4.0.5 on 2022-06-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orgs.client')),
            ],
            options={
                'unique_together': {('client_name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='№')),
                ('amount', models.FloatField(verbose_name='sum')),
                ('date', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orgs.organization')),
            ],
            options={
                'unique_together': {('organization', 'number')},
            },
        ),
    ]
